apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
spec: 
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim: 
            claimName: pvc
      containers:
        - name: wordpress-container
          image: wordpress:6.0.2
          envFrom:
            - secretRef:
                name: wordpress-secret
          volumeMounts:
            - name: volume-teste
              mountPath: "/var/www/html"
  selector:
    matchLabels:
      app: wordpress
  replicas: 2
