apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: labwordpress
  labels:
    app: wordpress-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /wordpress-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/no-proviser
          operator: In
          values:
           - docker-desktop
