apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  storageClassName: mysql
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
    type: DirectoryOrCreate