apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
spec:
  storageClassName: wordpress
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wordpress"
    type: DirectoryOrCreate