apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: senha do root aqui
  MYSQL_USER: user
  MYSQL_PASSWORD: senha do user aqui
  MYSQL_DATABASE: banco