apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: labwordpress
spec:
  selector: 
    app: wordpress
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: ClusterIP
