apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  namespace: labwordpress
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: mysql-persistent-storage-lab
          persistentVolumeClaim: 
            claimName: wordpress
      containers:
        - name: wordpress
          image: wordpress:6.0.2
          envFrom:
            - secretRef:
                name: wordpress
          ports:
          - containerPort: 80
            name: wordpress
          volumeMounts:
            - name: mysql-persistent-storage-lab
              mountPath: "/var/www/html"

