apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: labwordpress
spec:
  storageClassName: wordpress
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi