apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector: 
    app: wordpress
  ports:
    - name: http
      targetPort: 80
      port: 80
      nodePort: 30080
  type: NodePort
