apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: labwordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 
  selector:
    matchLabels:
      type: mysql

